name: weathernaut
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  auto_route: ^7.8.4
  geolocator: ^10.1.0
  retrofit: ^4.0.3  
  json_annotation: ^4.8.1
  mockito: ^5.4.2
  meta: ^1.9.1
  bloc_concurrency: ^0.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.4
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  generate: true
  assets: 
    - assets/images/weather/
