Map<String, dynamic> currentWeatherMap = {
  "location": {
    "name": "Hrodna",
    "region": "Hrodzyenskaya Voblasts'",
    "country": "Belarus",
    "lat": 53.68,
    "lon": 23.81,
    "tz_id": "Europe/Minsk",
    "localtime_epoch": 1700156394,
    "localtime": "2023-11-16 20:39"
  },
  "current": {
    "last_updated_epoch": 1700155800,
    "last_updated": "2023-11-16 20:30",
    "temp_c": 1,
    "temp_f": 33.8,
    "is_day": 0,
    "condition": {"text": "Overcast", "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png", "code": 1009},
    "wind_mph": 4.5,
    "wind_kph": 7.2,
    "wind_degree": 96,
    "wind_dir": "E",
    "pressure_mb": 1016,
    "pressure_in": 30.02,
    "precip_mm": 0,
    "precip_in": 0,
    "humidity": 73,
    "cloud": 91,
    "feelslike_c": -1.3,
    "feelslike_f": 29.6,
    "vis_km": 10,
    "vis_miles": 6,
    "uv": 1,
    "gust_mph": 6.5,
    "gust_kph": 10.5
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2023-11-16",
        "date_epoch": 1700092800,
        "day": {
          "maxtemp_c": 2.1,
          "maxtemp_f": 35.8,
          "mintemp_c": -0.6,
          "mintemp_f": 31,
          "avgtemp_c": 1,
          "avgtemp_f": 33.8,
          "maxwind_mph": 12.5,
          "maxwind_kph": 20.2,
          "totalprecip_mm": 0.11,
          "totalprecip_in": 0,
          "totalsnow_cm": 0.06,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 81,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 82,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Patchy rain possible",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
            "code": 1063
          },
          "uv": 1
        },
        "astro": {
          "sunrise": "08:52 AM",
          "sunset": "05:26 PM",
          "moonrise": "12:59 PM",
          "moonset": "06:55 PM",
          "moon_phase": "Waxing Crescent",
          "moon_illumination": 8,
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1700082000,
            "time": "2023-11-16 00:00",
            "temp_c": 2.1,
            "temp_f": 35.9,
            "is_day": 0,
            "condition": {
              "text": "Light snow showers",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/368.png",
              "code": 1255
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 343,
            "wind_dir": "NNW",
            "pressure_mb": 1011,
            "pressure_in": 29.85,
            "precip_mm": 0.03,
            "precip_in": 0,
            "humidity": 94,
            "cloud": 100,
            "feelslike_c": -2.6,
            "feelslike_f": 27.4,
            "windchill_c": -2.6,
            "windchill_f": 27.4,
            "heatindex_c": 2.1,
            "heatindex_f": 35.9,
            "dewpoint_c": 1.2,
            "dewpoint_f": 34.2,
            "will_it_rain": 0,
            "chance_of_rain": 62,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.2,
            "gust_kph": 27.6,
            "uv": 1
          },
          {
            "time_epoch": 1700085600,
            "time": "2023-11-16 01:00",
            "temp_c": 2,
            "temp_f": 35.5,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 11.9,
            "wind_kph": 19.1,
            "wind_degree": 341,
            "wind_dir": "NNW",
            "pressure_mb": 1011,
            "pressure_in": 29.86,
            "precip_mm": 0.01,
            "precip_in": 0,
            "humidity": 90,
            "cloud": 100,
            "feelslike_c": -2.7,
            "feelslike_f": 27.2,
            "windchill_c": -2.7,
            "windchill_f": 27.2,
            "heatindex_c": 2,
            "heatindex_f": 35.5,
            "dewpoint_c": 0.5,
            "dewpoint_f": 32.8,
            "will_it_rain": 0,
            "chance_of_rain": 62,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.1,
            "gust_kph": 25.9,
            "uv": 1
          },
          {
            "time_epoch": 1700089200,
            "time": "2023-11-16 02:00",
            "temp_c": 1.8,
            "temp_f": 35.2,
            "is_day": 0,
            "condition": {"text": "Overcast", "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png", "code": 1009},
            "wind_mph": 10.3,
            "wind_kph": 16.6,
            "wind_degree": 336,
            "wind_dir": "NNW",
            "pressure_mb": 1012,
            "pressure_in": 29.88,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 87,
            "cloud": 90,
            "feelslike_c": -2.5,
            "feelslike_f": 27.5,
            "windchill_c": -2.5,
            "windchill_f": 27.5,
            "heatindex_c": 1.8,
            "heatindex_f": 35.2,
            "dewpoint_c": -0.2,
            "dewpoint_f": 31.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.4,
            "gust_kph": 23.2,
            "uv": 1
          },
          {
            "time_epoch": 1700092800,
            "time": "2023-11-16 03:00",
            "temp_c": 1,
            "temp_f": 33.8,
            "is_day": 0,
            "condition": {"text": "Cloudy", "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png", "code": 1006},
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 327,
            "wind_dir": "NNW",
            "pressure_mb": 1012,
            "pressure_in": 29.9,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 89,
            "cloud": 64,
            "feelslike_c": -3.2,
            "feelslike_f": 26.3,
            "windchill_c": -3.2,
            "windchill_f": 26.3,
            "heatindex_c": 1,
            "heatindex_f": 33.8,
            "dewpoint_c": -0.7,
            "dewpoint_f": 30.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.7,
            "gust_kph": 22,
            "uv": 1
          },
          {
            "time_epoch": 1700096400,
            "time": "2023-11-16 04:00",
            "temp_c": 0.2,
            "temp_f": 32.4,
            "is_day": 0,
            "condition": {"text": "Cloudy", "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png", "code": 1006},
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 320,
            "wind_dir": "NW",
            "pressure_mb": 1013,
            "pressure_in": 29.92,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 90,
            "cloud": 68,
            "feelslike_c": -3.6,
            "feelslike_f": 25.6,
            "windchill_c": -3.6,
            "windchill_f": 25.6,
            "heatindex_c": 0.2,
            "heatindex_f": 32.4,
            "dewpoint_c": -1.1,
            "dewpoint_f": 30,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.3,
            "gust_kph": 19.8,
            "uv": 1
          },
          {
            "time_epoch": 1700100000,
            "time": "2023-11-16 05:00",
            "temp_c": -0.5,
            "temp_f": 31.1,
            "is_day": 0,
            "condition": {"text": "Cloudy", "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png", "code": 1006},
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 319,
            "wind_dir": "NW",
            "pressure_mb": 1014,
            "pressure_in": 29.93,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 91,
            "cloud": 64,
            "feelslike_c": -4.5,
            "feelslike_f": 23.8,
            "windchill_c": -4.5,
            "windchill_f": 23.8,
            "heatindex_c": -0.5,
            "heatindex_f": 31.1,
            "dewpoint_c": -1.8,
            "dewpoint_f": 28.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.7,
            "gust_kph": 20.4,
            "uv": 1
          },
          {
            "time_epoch": 1700103600,
            "time": "2023-11-16 06:00",
            "temp_c": -0.6,
            "temp_f": 31,
            "is_day": 0,
            "condition": {"text": "Cloudy", "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png", "code": 1006},
            "wind_mph": 6.9,
            "wind_kph": 11.2,
            "wind_degree": 318,
            "wind_dir": "NW",
            "pressure_mb": 1014,
            "pressure_in": 29.94,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 89,
            "cloud": 67,
            "feelslike_c": -4.3,
            "feelslike_f": 24.3,
            "windchill_c": -4.3,
            "windchill_f": 24.3,
            "heatindex_c": -0.6,
            "heatindex_f": 31,
            "dewpoint_c": -2.1,
            "dewpoint_f": 28.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.7,
            "gust_kph": 18.8,
            "uv": 1
          },
          {
            "time_epoch": 1700107200,
            "time": "2023-11-16 07:00",
            "temp_c": -0.5,
            "temp_f": 31.1,
            "is_day": 0,
            "condition": {"text": "Cloudy", "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png", "code": 1006},
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 312,
            "wind_dir": "NW",
            "pressure_mb": 1015,
            "pressure_in": 29.96,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 89,
            "cloud": 63,
            "feelslike_c": -4,
            "feelslike_f": 24.9,
            "windchill_c": -4,
            "windchill_f": 24.9,
            "heatindex_c": -0.5,
            "heatindex_f": 31.1,
            "dewpoint_c": -2.1,
            "dewpoint_f": 28.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.6,
            "gust_kph": 17.1,
            "uv": 1
          },
          {
            "time_epoch": 1700110800,
            "time": "2023-11-16 08:00",
            "temp_c": -0.5,
            "temp_f": 31.1,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 5.6,
            "wind_kph": 9,
            "wind_degree": 310,
            "wind_dir": "NW",
            "pressure_mb": 1015,
            "pressure_in": 29.97,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 89,
            "cloud": 54,
            "feelslike_c": -3.6,
            "feelslike_f": 25.5,
            "windchill_c": -3.6,
            "windchill_f": 25.5,
            "heatindex_c": -0.5,
            "heatindex_f": 31.1,
            "dewpoint_c": -2,
            "dewpoint_f": 28.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.4,
            "gust_kph": 15.1,
            "uv": 1
          },
          {
            "time_epoch": 1700114400,
            "time": "2023-11-16 09:00",
            "temp_c": 0.1,
            "temp_f": 32.2,
            "is_day": 1,
            "condition": {"text": "Cloudy", "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png", "code": 1006},
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 308,
            "wind_dir": "NW",
            "pressure_mb": 1015,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 88,
            "cloud": 71,
            "feelslike_c": -2.7,
            "feelslike_f": 27.1,
            "windchill_c": -2.7,
            "windchill_f": 27.1,
            "heatindex_c": 0.1,
            "heatindex_f": 32.2,
            "dewpoint_c": -1.6,
            "dewpoint_f": 29.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.8,
            "gust_kph": 12.5,
            "uv": 1
          },
          {
            "time_epoch": 1700118000,
            "time": "2023-11-16 10:00",
            "temp_c": 1,
            "temp_f": 33.9,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 325,
            "wind_dir": "NW",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0.01,
            "precip_in": 0,
            "humidity": 86,
            "cloud": 83,
            "feelslike_c": -2.1,
            "feelslike_f": 28.3,
            "windchill_c": -2.1,
            "windchill_f": 28.3,
            "heatindex_c": 1.1,
            "heatindex_f": 33.9,
            "dewpoint_c": -1.1,
            "dewpoint_f": 30.1,
            "will_it_rain": 1,
            "chance_of_rain": 82,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.3,
            "gust_kph": 13.3,
            "uv": 1
          },
          {
            "time_epoch": 1700121600,
            "time": "2023-11-16 11:00",
            "temp_c": 1.7,
            "temp_f": 35.1,
            "is_day": 1,
            "condition": {"text": "Light snow", "icon": "//cdn.weatherapi.com/weather/64x64/day/326.png", "code": 1213},
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 334,
            "wind_dir": "NNW",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0.02,
            "precip_in": 0,
            "humidity": 83,
            "cloud": 100,
            "feelslike_c": -1.3,
            "feelslike_f": 29.6,
            "windchill_c": -1.3,
            "windchill_f": 29.6,
            "heatindex_c": 1.7,
            "heatindex_f": 35.1,
            "dewpoint_c": -0.8,
            "dewpoint_f": 30.5,
            "will_it_rain": 1,
            "chance_of_rain": 76,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.3,
            "gust_kph": 13.3,
            "uv": 1
          },
          {
            "time_epoch": 1700125200,
            "time": "2023-11-16 12:00",
            "temp_c": 2.1,
            "temp_f": 35.8,
            "is_day": 1,
            "condition": {"text": "Light snow", "icon": "//cdn.weatherapi.com/weather/64x64/day/326.png", "code": 1213},
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 333,
            "wind_dir": "NNW",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0.03,
            "precip_in": 0,
            "humidity": 78,
            "cloud": 100,
            "feelslike_c": -0.8,
            "feelslike_f": 30.5,
            "windchill_c": -0.8,
            "windchill_f": 30.5,
            "heatindex_c": 2.1,
            "heatindex_f": 35.8,
            "dewpoint_c": -1.3,
            "dewpoint_f": 29.6,
            "will_it_rain": 1,
            "chance_of_rain": 75,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.9,
            "gust_kph": 12.7,
            "uv": 1
          },
          {
            "time_epoch": 1700128800,
            "time": "2023-11-16 13:00",
            "temp_c": 2.1,
            "temp_f": 35.8,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 333,
            "wind_dir": "NNW",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0.01,
            "precip_in": 0,
            "humidity": 74,
            "cloud": 100,
            "feelslike_c": -0.9,
            "feelslike_f": 30.4,
            "windchill_c": -0.9,
            "windchill_f": 30.4,
            "heatindex_c": 2.1,
            "heatindex_f": 35.8,
            "dewpoint_c": -2,
            "dewpoint_f": 28.5,
            "will_it_rain": 1,
            "chance_of_rain": 76,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.4,
            "gust_kph": 13.5,
            "uv": 1
          },
          {
            "time_epoch": 1700132400,
            "time": "2023-11-16 14:00",
            "temp_c": 1.9,
            "temp_f": 35.4,
            "is_day": 1,
            "condition": {"text": "Overcast", "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png", "code": 1009},
            "wind_mph": 6,
            "wind_kph": 9.7,
            "wind_degree": 338,
            "wind_dir": "NNW",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 73,
            "cloud": 100,
            "feelslike_c": -1,
            "feelslike_f": 30.2,
            "windchill_c": -1,
            "windchill_f": 30.2,
            "heatindex_c": 1.9,
            "heatindex_f": 35.4,
            "dewpoint_c": -2.4,
            "dewpoint_f": 27.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8,
            "gust_kph": 12.9,
            "uv": 1
          },
          {
            "time_epoch": 1700136000,
            "time": "2023-11-16 15:00",
            "temp_c": 1.6,
            "temp_f": 34.8,
            "is_day": 1,
            "condition": {"text": "Overcast", "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png", "code": 1009},
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 339,
            "wind_dir": "NNW",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 72,
            "cloud": 100,
            "feelslike_c": -1,
            "feelslike_f": 30.2,
            "windchill_c": -1,
            "windchill_f": 30.2,
            "heatindex_c": 1.6,
            "heatindex_f": 34.8,
            "dewpoint_c": -2.9,
            "dewpoint_f": 26.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7,
            "gust_kph": 11.2,
            "uv": 1
          },
          {
            "time_epoch": 1700139600,
            "time": "2023-11-16 16:00",
            "temp_c": 1.3,
            "temp_f": 34.4,
            "is_day": 1,
            "condition": {"text": "Overcast", "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png", "code": 1009},
            "wind_mph": 4.5,
            "wind_kph": 7.2,
            "wind_degree": 355,
            "wind_dir": "N",
            "pressure_mb": 1016,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 73,
            "cloud": 96,
            "feelslike_c": -0.9,
            "feelslike_f": 30.3,
            "windchill_c": -0.9,
            "windchill_f": 30.3,
            "heatindex_c": 1.3,
            "heatindex_f": 34.4,
            "dewpoint_c": -2.9,
            "dewpoint_f": 26.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.2,
            "gust_kph": 9.9,
            "uv": 1
          },
          {
            "time_epoch": 1700143200,
            "time": "2023-11-16 17:00",
            "temp_c": 1.2,
            "temp_f": 34.2,
            "is_day": 1,
            "condition": {"text": "Overcast", "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png", "code": 1009},
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 14,
            "wind_dir": "NNE",
            "pressure_mb": 1017,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 73,
            "cloud": 97,
            "feelslike_c": -0.5,
            "feelslike_f": 31.1,
            "windchill_c": -0.5,
            "windchill_f": 31.1,
            "heatindex_c": 1.2,
            "heatindex_f": 34.2,
            "dewpoint_c": -3.1,
            "dewpoint_f": 26.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5,
            "gust_kph": 8.1,
            "uv": 1
          },
          {
            "time_epoch": 1700146800,
            "time": "2023-11-16 18:00",
            "temp_c": 1.2,
            "temp_f": 34.2,
            "is_day": 0,
            "condition": {"text": "Overcast", "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png", "code": 1009},
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 48,
            "wind_dir": "NE",
            "pressure_mb": 1017,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 73,
            "cloud": 97,
            "feelslike_c": -0.6,
            "feelslike_f": 31,
            "windchill_c": -0.6,
            "windchill_f": 31,
            "heatindex_c": 1.2,
            "heatindex_f": 34.2,
            "dewpoint_c": -3.1,
            "dewpoint_f": 26.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5,
            "gust_kph": 8.1,
            "uv": 1
          },
          {
            "time_epoch": 1700150400,
            "time": "2023-11-16 19:00",
            "temp_c": 1.1,
            "temp_f": 33.9,
            "is_day": 0,
            "condition": {"text": "Overcast", "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png", "code": 1009},
            "wind_mph": 4.5,
            "wind_kph": 7.2,
            "wind_degree": 73,
            "wind_dir": "ENE",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 73,
            "cloud": 92,
            "feelslike_c": -1.2,
            "feelslike_f": 29.8,
            "windchill_c": -1.2,
            "windchill_f": 29.8,
            "heatindex_c": 1.1,
            "heatindex_f": 33.9,
            "dewpoint_c": -3.2,
            "dewpoint_f": 26.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.4,
            "gust_kph": 10.3,
            "uv": 1
          },
          {
            "time_epoch": 1700154000,
            "time": "2023-11-16 20:00",
            "temp_c": 1,
            "temp_f": 33.8,
            "is_day": 0,
            "condition": {"text": "Overcast", "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png", "code": 1009},
            "wind_mph": 4.5,
            "wind_kph": 7.2,
            "wind_degree": 96,
            "wind_dir": "E",
            "pressure_mb": 1016,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 73,
            "cloud": 91,
            "feelslike_c": -1.3,
            "feelslike_f": 29.6,
            "windchill_c": -1.3,
            "windchill_f": 29.6,
            "heatindex_c": 1,
            "heatindex_f": 33.8,
            "dewpoint_c": -3.3,
            "dewpoint_f": 26.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.5,
            "gust_kph": 10.5,
            "uv": 1
          },
          {
            "time_epoch": 1700157600,
            "time": "2023-11-16 21:00",
            "temp_c": 1,
            "temp_f": 33.9,
            "is_day": 0,
            "condition": {"text": "Cloudy", "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png", "code": 1006},
            "wind_mph": 5.6,
            "wind_kph": 9,
            "wind_degree": 105,
            "wind_dir": "ESE",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 71,
            "cloud": 73,
            "feelslike_c": -1.8,
            "feelslike_f": 28.7,
            "windchill_c": -1.8,
            "windchill_f": 28.7,
            "heatindex_c": 1,
            "heatindex_f": 33.9,
            "dewpoint_c": -3.5,
            "dewpoint_f": 25.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.2,
            "gust_kph": 13.2,
            "uv": 1
          },
          {
            "time_epoch": 1700161200,
            "time": "2023-11-16 22:00",
            "temp_c": 1,
            "temp_f": 33.8,
            "is_day": 0,
            "condition": {"text": "Cloudy", "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png", "code": 1006},
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 123,
            "wind_dir": "ESE",
            "pressure_mb": 1016,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 71,
            "cloud": 73,
            "feelslike_c": -1.9,
            "feelslike_f": 28.5,
            "windchill_c": -1.9,
            "windchill_f": 28.5,
            "heatindex_c": 1,
            "heatindex_f": 33.8,
            "dewpoint_c": -3.7,
            "dewpoint_f": 25.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.8,
            "gust_kph": 14.1,
            "uv": 1
          },
          {
            "time_epoch": 1700164800,
            "time": "2023-11-16 23:00",
            "temp_c": 0.8,
            "temp_f": 33.5,
            "is_day": 0,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 114,
            "wind_dir": "ESE",
            "pressure_mb": 1016,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 74,
            "cloud": 57,
            "feelslike_c": -2.2,
            "feelslike_f": 28.1,
            "windchill_c": -2.2,
            "windchill_f": 28.1,
            "heatindex_c": 0.8,
            "heatindex_f": 33.5,
            "dewpoint_c": -3.4,
            "dewpoint_f": 26,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.1,
            "gust_kph": 14.6,
            "uv": 1
          }
        ]
      }
    ]
  }
};
