Map<String, dynamic> weaklyWeatherMap = {
  "location": {
    "name": "Hrodna",
    "region": "Hrodzyenskaya Voblasts'",
    "country": "Belarus",
    "lat": 53.68,
    "lon": 23.81,
    "tz_id": "Europe/Minsk",
    "localtime_epoch": 1700150259,
    "localtime": "2023-11-16 18:57"
  },
  "current": {
    "last_updated_epoch": 1700149500,
    "last_updated": "2023-11-16 18:45",
    "temp_c": 0.9,
    "temp_f": 33.6,
    "is_day": 0,
    "condition": {"text": "Overcast", "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png", "code": 1009},
    "wind_mph": 4,
    "wind_kph": 6.5,
    "wind_degree": 54,
    "wind_dir": "NE",
    "pressure_mb": 1016,
    "pressure_in": 30.01,
    "precip_mm": 0,
    "precip_in": 0,
    "humidity": 74,
    "cloud": 98,
    "feelslike_c": -1.2,
    "feelslike_f": 29.8,
    "vis_km": 10,
    "vis_miles": 6,
    "uv": 1,
    "gust_mph": 5.6,
    "gust_kph": 9
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2023-11-16",
        "date_epoch": 1700092800,
        "day": {
          "maxtemp_c": 2.1,
          "maxtemp_f": 35.8,
          "mintemp_c": -0.6,
          "mintemp_f": 31,
          "avgtemp_c": 1,
          "avgtemp_f": 33.7,
          "maxwind_mph": 12.5,
          "maxwind_kph": 20.2,
          "totalprecip_mm": 0.12,
          "totalprecip_in": 0,
          "totalsnow_cm": 0.08,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 81,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 87,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Light freezing rain",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/311.png",
            "code": 1198
          },
          "uv": 1
        },
        "astro": {
          "sunrise": "08:52 AM",
          "sunset": "05:26 PM",
          "moonrise": "12:59 PM",
          "moonset": "06:55 PM",
          "moon_phase": "Waxing Crescent",
          "moon_illumination": 8,
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": []
      },
      {
        "date": "2023-11-17",
        "date_epoch": 1700179200,
        "day": {
          "maxtemp_c": 2.2,
          "maxtemp_f": 35.9,
          "mintemp_c": -1.4,
          "mintemp_f": 29.5,
          "avgtemp_c": -0.1,
          "avgtemp_f": 31.9,
          "maxwind_mph": 12.3,
          "maxwind_kph": 19.8,
          "totalprecip_mm": 0,
          "totalprecip_in": 0,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 75,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
          },
          "uv": 2
        },
        "astro": {
          "sunrise": "08:54 AM",
          "sunset": "05:25 PM",
          "moonrise": "01:54 PM",
          "moonset": "08:07 PM",
          "moon_phase": "Waxing Crescent",
          "moon_illumination": 15,
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": []
      },
      {
        "date": "2023-11-18",
        "date_epoch": 1700265600,
        "day": {
          "maxtemp_c": 1.7,
          "maxtemp_f": 35,
          "mintemp_c": -2.4,
          "mintemp_f": 27.7,
          "avgtemp_c": -1,
          "avgtemp_f": 30.2,
          "maxwind_mph": 7.6,
          "maxwind_kph": 12.2,
          "totalprecip_mm": 0,
          "totalprecip_in": 0,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 76,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
          },
          "uv": 2
        },
        "astro": {
          "sunrise": "08:56 AM",
          "sunset": "05:23 PM",
          "moonrise": "02:30 PM",
          "moonset": "09:34 PM",
          "moon_phase": "Waxing Crescent",
          "moon_illumination": 24,
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": []
      },
      {
        "date": "2023-11-19",
        "date_epoch": 1700352000,
        "day": {
          "maxtemp_c": 0.5,
          "maxtemp_f": 33,
          "mintemp_c": -2.4,
          "mintemp_f": 27.7,
          "avgtemp_c": -0.8,
          "avgtemp_f": 30.5,
          "maxwind_mph": 12.8,
          "maxwind_kph": 20.5,
          "totalprecip_mm": 2.86,
          "totalprecip_in": 0.11,
          "totalsnow_cm": 2.42,
          "avgvis_km": 6.8,
          "avgvis_miles": 4,
          "avghumidity": 92,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 67,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 39,
          "condition": {
            "text": "Moderate snow",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/332.png",
            "code": 1219
          },
          "uv": 1
        },
        "astro": {
          "sunrise": "08:58 AM",
          "sunset": "05:22 PM",
          "moonrise": "02:54 PM",
          "moonset": "11:06 PM",
          "moon_phase": "Waxing Crescent",
          "moon_illumination": 34,
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": []
      },
      {
        "date": "2023-11-20",
        "date_epoch": 1700438400,
        "day": {
          "maxtemp_c": 0.4,
          "maxtemp_f": 32.7,
          "mintemp_c": -0.2,
          "mintemp_f": 31.6,
          "avgtemp_c": 0.2,
          "avgtemp_f": 32.3,
          "maxwind_mph": 11.2,
          "maxwind_kph": 18,
          "totalprecip_mm": 3.1,
          "totalprecip_in": 0.12,
          "totalsnow_cm": 0.83,
          "avgvis_km": 7.1,
          "avgvis_miles": 4,
          "avghumidity": 98,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 78,
          "daily_will_it_snow": 1,
          "daily_chance_of_snow": 74,
          "condition": {"text": "Light snow", "icon": "//cdn.weatherapi.com/weather/64x64/day/326.png", "code": 1213},
          "uv": 1
        },
        "astro": {
          "sunrise": "09:00 AM",
          "sunset": "05:21 PM",
          "moonrise": "03:10 PM",
          "moonset": "No moonset",
          "moon_phase": "First Quarter",
          "moon_illumination": 45,
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": []
      },
      {
        "date": "2023-11-21",
        "date_epoch": 1700524800,
        "day": {
          "maxtemp_c": -1,
          "maxtemp_f": 30.3,
          "mintemp_c": -5,
          "mintemp_f": 23,
          "avgtemp_c": -1.2,
          "avgtemp_f": 29.9,
          "maxwind_mph": 11.2,
          "maxwind_kph": 18,
          "totalprecip_mm": 5.1,
          "totalprecip_in": 0.2,
          "totalsnow_cm": 3.99,
          "avgvis_km": 4.7,
          "avgvis_miles": 2,
          "avghumidity": 98,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 73,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 54,
          "condition": {"text": "Heavy snow", "icon": "//cdn.weatherapi.com/weather/64x64/day/338.png", "code": 1225},
          "uv": 1
        },
        "astro": {
          "sunrise": "09:01 AM",
          "sunset": "05:19 PM",
          "moonrise": "03:22 PM",
          "moonset": "12:38 AM",
          "moon_phase": "Waxing Gibbous",
          "moon_illumination": 56,
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": []
      },
      {
        "date": "2023-11-22",
        "date_epoch": 1700611200,
        "day": {
          "maxtemp_c": -3.6,
          "maxtemp_f": 25.5,
          "mintemp_c": -9.6,
          "mintemp_f": 14.8,
          "avgtemp_c": -7,
          "avgtemp_f": 19.4,
          "maxwind_mph": 11,
          "maxwind_kph": 17.6,
          "totalprecip_mm": 0.01,
          "totalprecip_in": 0,
          "totalsnow_cm": 0,
          "avgvis_km": 4.5,
          "avgvis_miles": 2,
          "avghumidity": 95,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {"text": "Freezing fog", "icon": "//cdn.weatherapi.com/weather/64x64/day/260.png", "code": 1147},
          "uv": 1
        },
        "astro": {
          "sunrise": "09:03 AM",
          "sunset": "05:18 PM",
          "moonrise": "03:32 PM",
          "moonset": "02:07 AM",
          "moon_phase": "Waxing Gibbous",
          "moon_illumination": 67,
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": []
      }
    ]
  }
};
