// Mocks generated by Mockito 5.4.2 from annotations
// in weathernaut/test/api_test/weather_api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i2;
import 'package:weathernaut/src/core/data/data_sources/remote/weather_api_service.dart'
    as _i3;
import 'package:weathernaut/src/core/data/models/current_weather.dart' as _i5;
import 'package:weathernaut/src/core/data/models/weakly_weather.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherApiService extends _i1.Mock implements _i3.WeatherApiService {
  @override
  _i4.Future<_i2.HttpResponse<_i5.CurrentWeatherModel>>
      getCurrentWeatherForecastFromLocation({
    required String? key,
    required String? q,
    required int? days,
    required int? tp,
    required String? lang,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getCurrentWeatherForecastFromLocation,
              [],
              {
                #key: key,
                #q: q,
                #days: days,
                #tp: tp,
                #lang: lang,
              },
            ),
            returnValue:
                _i4.Future<_i2.HttpResponse<_i5.CurrentWeatherModel>>.value(
                    _FakeHttpResponse_0<_i5.CurrentWeatherModel>(
              this,
              Invocation.method(
                #getCurrentWeatherForecastFromLocation,
                [],
                {
                  #key: key,
                  #q: q,
                  #days: days,
                  #tp: tp,
                  #lang: lang,
                },
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i2.HttpResponse<_i5.CurrentWeatherModel>>.value(
                    _FakeHttpResponse_0<_i5.CurrentWeatherModel>(
              this,
              Invocation.method(
                #getCurrentWeatherForecastFromLocation,
                [],
                {
                  #key: key,
                  #q: q,
                  #days: days,
                  #tp: tp,
                  #lang: lang,
                },
              ),
            )),
          ) as _i4.Future<_i2.HttpResponse<_i5.CurrentWeatherModel>>);

  @override
  _i4.Future<_i2.HttpResponse<_i6.WeaklyWeatherModel>>
      getWeaklyWeatherForecastFromLocation({
    required String? key,
    required String? q,
    required int? days,
    required int? hour,
    required String? lang,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getWeaklyWeatherForecastFromLocation,
              [],
              {
                #key: key,
                #q: q,
                #days: days,
                #hour: hour,
                #lang: lang,
              },
            ),
            returnValue:
                _i4.Future<_i2.HttpResponse<_i6.WeaklyWeatherModel>>.value(
                    _FakeHttpResponse_0<_i6.WeaklyWeatherModel>(
              this,
              Invocation.method(
                #getWeaklyWeatherForecastFromLocation,
                [],
                {
                  #key: key,
                  #q: q,
                  #days: days,
                  #hour: hour,
                  #lang: lang,
                },
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i2.HttpResponse<_i6.WeaklyWeatherModel>>.value(
                    _FakeHttpResponse_0<_i6.WeaklyWeatherModel>(
              this,
              Invocation.method(
                #getWeaklyWeatherForecastFromLocation,
                [],
                {
                  #key: key,
                  #q: q,
                  #days: days,
                  #hour: hour,
                  #lang: lang,
                },
              ),
            )),
          ) as _i4.Future<_i2.HttpResponse<_i6.WeaklyWeatherModel>>);
}
